### ISSUE TITLE
Pokazivač `this`

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-021-space-mess#1]
Osim ako postoji lokalna promenljiva koja ne dozvoljava pristup klasnoj (i u još nekim veoma retkim situacijama), nije potrebno (čak se smatra lošim stilom) pisati `this->`.

**Comment by ivke080** [comment]
Hvala na sugestiji.Radim cesto php sa strane, sto za neke sitne poslice,
sto za sebe, a kao sto znate tamo je $this neophodno u okviru klasa, pa mi
po navici ostalo to. Ispravicu gde bude trebalo :)

**Comment by ivan-cukic-matf** [comment]
Heh, PHP je uništio mnogo dobrih programera :)
